# Generated by Django 5.2.7 on 2025-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=64)),
                ('mac', models.CharField(blank=True, default='', max_length=64)),
                ('hostname', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_mbps', models.FloatField(default=0)),
                ('upload_mbps', models.FloatField(default=0)),
                ('ping_ms', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=64)),
                ('download_mbps', models.FloatField(default=0)),
                ('upload_mbps', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ssid', models.CharField(max_length=128)),
                ('bssid', models.CharField(blank=True, default='', max_length=64)),
                ('signal', models.IntegerField(default=0)),
                ('channel', models.IntegerField(default=0)),
                ('security', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
